'use client'

import type {Metadata} from 'next'
import './globals.css'
import {Navbar} from "@/components/Navbar";
import {SideBar} from "@/components/SideBar"
import React from "react";
import {RecoilRoot, useRecoilState} from "recoil";
import {switchState} from "@/recoil/recoilAtoms"
import Layout from "@/components/Layout";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  // const isLightMode = useRecoilState(switchState)
  return (
    <RecoilRoot>
      <Layout children={children} />
    </RecoilRoot>
  )
}
//nextjs에서 다크모드를 구현하고싶은데 사용자가 입력한 기본값은 false인 토글 상태에 따라서 false일때는 일반모드 true일때 darkmode를 적용해주고싶은데 layout.ts에서 지금 'use client'를 사용할 수 없는 상태란말이야 그래서 server side rendering을 사용해야하는데