import type {Metadata} from 'next'
import './globals.css'
import {Navbar} from "@/components/Navbar";
import {SideBar} from "@/components/SideBar"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html>
    <body className="flex flex-col h-screen">
    <div className="flex-0">
      <Navbar/>
    </div>
    <div className="flex flex-1">
      <div className="bg-gray-100 p-4 w-48 flex-shrink-0">
        <SideBar/>
      </div>
      <div className="flex-1 p-4">
        {children}
      </div>
    </div>

    </body>
    </html>
  )
}
